### ISSUE TITLE
how to run unit tests ?

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1489] opened 2021-11-30 13:39 UTC
Hi,
I've been trying to run the unit tests locally, with
```bash
git clone git@github.com:alpaka-group/alpaka.git -b 0.8.0-rc1 alpaka-0.8.0-rc1
mkdir build
cd build
cmake -DBUILD_TESTING=on -DCMAKE_VERBOSE_MAKEFILE=on ../alpaka-0.8.0-rc1
make
```
but it fails with
```
...
[ 20%] Building CXX object test/analysis/headerCheck/CMakeFiles/headerCheckTest.dir/src/example/ExampleDefaultAcc.hpp.cpp.o
cd /home/fwyzard/src/alpaka-group/x/build/test/analysis/headerCheck && /usr/bin/c++ -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=47 -DALPAKA_DEBUG=0 -DALPAKA_DEBUG_OFFLOAD_ASSUME_HOST -DALPAKA_OFFLOAD_MAX_BLOCK_SIZE=256 -DBOOST_ALL_NO_LIB -DCATCH_CONFIG_FAST_COMPILE -I/home/fwyzard/src/alpaka-group/x/alpaka-0.8.0-rc1/include -isystem /home/fwyzard/src/alpaka-group/x/alpaka-0.8.0-rc1/test/catch_main/../../thirdParty/catch2/include -Wall -Wextra -pedantic -Werror -Wdouble-promotion -Wmissing-include-dirs -Wconversion -Wunknown-pragmas -Wstrict-overflow=2 -Wtrampolines -Wfloat-equal -Wundef -Wshadow -Wcast-qual -Wcast-align -Wwrite-strings -Wsign-conversion -Wvector-operation-performance -Wzero-as-null-pointer-constant -Wdate-time -Wuseless-cast -Wlogical-op -Wno-aggressive-loop-optimizations -Wmissing-declarations -Wno-multichar -Wopenmp-simd -Wpacked -Wredundant-decls -Wdisabled-optimization -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wctor-dtor-privacy -Wdelete-non-virtual-dtor -Wliteral-suffix -Wnon-virtual-dtor -Woverloaded-virtual -Wsign-promo -Wconditionally-supported -Wnoexcept -Wold-style-cast -Wsuggest-final-types -Wsuggest-final-methods -Wnormalized -Wformat-signedness -Wnull-dereference -Wduplicated-cond -Wsubobject-linkage -Walloc-zero -Walloca -Wcast-align=strict -o CMakeFiles/headerCheckTest.dir/src/example/ExampleDefaultAcc.hpp.cpp.o -c /home/fwyzard/src/alpaka-group/x/build/test/analysis/headerCheck/src/example/ExampleDefaultAcc.hpp.cpp
In file included from /home/fwyzard/src/alpaka-group/x/build/test/analysis/headerCheck/src/example/ExampleDefaultAcc.hpp.cpp:1:
/home/fwyzard/src/alpaka-group/x/alpaka-0.8.0-rc1/include/alpaka/example/ExampleDefaultAcc.hpp:50:6: error: #warning is a GCC extension [-Werror]
   50 | #    warning "No supported backend selected."
      |      ^~~~~~~
/home/fwyzard/src/alpaka-group/x/alpaka-0.8.0-rc1/include/alpaka/example/ExampleDefaultAcc.hpp:50:6: error: #warning "No supported backend selected." [-Werror=cpp]
cc1plus: all warnings being treated as errors
make[2]: *** [test/analysis/headerCheck/CMakeFiles/headerCheckTest.dir/build.make:1151: test/analysis/headerCheck/CMakeFiles/headerCheckTest.dir/src/example/ExampleDefaultAcc.hpp.cpp.o] Error 1
make[2]: Leaving directory '/home/fwyzard/src/alpaka-group/x/build'
make[1]: *** [CMakeFiles/Makefile2:1705: test/analysis/headerCheck/CMakeFiles/headerCheckTest.dir/all] Error 2
make[1]: Leaving directory '/home/fwyzard/src/alpaka-group/x/build'
make: *** [Makefile:163: all] Error 2
```

This happens both with the `0.8.0-rc1` branch and with the `develop` branch, both on Ubuntu 21.10 (with gcc 11.2) and CentOS 8.4 (with gcc 10.2).

I assume I am doing something wrong to build the unit tests, but I couldn't found any actual documentation on how to do it :-/

**Comment by sbastrakov** [comment] 2021-11-30 13:52
Hello @fwyzard ,

The issue is, you did not enable any alpaka backends when configuring. You should add `-DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE=ON` and similar for other backends you want to use to the cmake command. More details about these flags are in [this doc page](https://alpaka.readthedocs.io/en/latest/advanced/cmake.html#).

However, you are right that the docs should also have an explicit command on how to build and run unit tests, somewhere in front. We had it on the workshop slides, but probably didn't translate to reaqthedocs (or it is well hidden therE)

**Comment by bernhardmgruber** [comment] 2021-11-30 13:52
People wiser than me have decided at some point to not enable any of the backends by default. So the only thing missing in your case is to enable at least the serial backend with `-DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE=ON`. You are free to enable additional backends, just check with `ccmake ../alpaka-0.8.0-rc1`.

It seems there is really no good documentation on this matter, we should add it somewhere.

**Comment by sbastrakov** [comment] 2021-11-30 13:52
Lol, thought the same thing at same time @bernhardmgruber

**Comment by fwyzard** [comment] 2021-11-30 14:13
Thanks @sbastrakov @bernhardmgruber , enabling the backends seems to work.

**Comment by j-stephan** [comment] 2021-12-07 14:49
Closing this issue. We will monitor this in #1513.

**Closed as completed** 2021-12-07 14:54 UTC
Labels: Type:Question, Type:Install
