### ISSUE TITLE
Visual Studio 2017 15.9 (regression): OpenMP not working in variadic templates

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#726] opened 2019-01-05 07:42 UTC

**Comment by BenjaminW3** [comment] 2019-01-05 07:48
Our internal sanity check is triggered saying: `The OpenMP 2.0 runtime did not use the number of threads that had been required!`

**Comment by sbastrakov** [comment] 2019-01-07 08:16
This is just a guess, ofc the reason may be completely unrelated.

Strictly speaking, [the failing check](https://github.com/ComputationalRadiationPhysics/alpaka/blob/27a7e11bf4d7096b8ed9eea7f3612fcc78b3cc4e/include/alpaka/exec/ExecCpuOmp2Threads.hpp#L194) actually does not *always* have to hold. According to [the spec (page 9 in the internal numbering, paragraph from line 28)](https://www.openmp.org/wp-content/uploads/cspec20.pdf), in case the requested number in the `#pragma omp parallel num_threads(...)` exceeds the number available on the system, the behaviour is implementation-defined. So it is possible the CI system (or due to our configuration) does not provide enough resources and this check fails.

**Comment by BenjaminW3** [comment] 2019-01-07 08:20
Yes, I know that this is possible. Therefore we added the check because the result would be invalid in case the runtime used a different number of threads.
I was able to reproduce this locally and added a check for `omp_in_parallel` which always returns false for both OpenMP 2.0 backends. So there seems to be something wrong with the Windows OpenMP build.

**Comment by sbastrakov** [comment] 2019-01-07 08:37
@BenjaminW3 sure, I see the point of that. But what if due to some unfortunate configuration we request more threads than the system supports (dunno, have a hard time imagining that myself). 

Btw maybe add info about the requested and actual number of threads to the exception message?

**Comment by ax3l** [comment] 2019-01-07 08:40
Yes, the situation in travis: more physical cores (N>2) "visible" than accessible (2). Could confuse OpenMP startup. Maybe we just export `OMP_NUM_THREADS` to e.g. 2?

**Comment by sbastrakov** [comment] 2019-01-07 08:41
Don't we do it already? iirc that's the standard travis recommendation for OpenMP-enabled codes.

Edit: I meant not that I'm sure we do it already (currently I don't know that), but I'm sure we should do it.

**Comment by BenjaminW3** [comment] 2019-01-14 18:21
@sbastrakov found the reason and reported it to microsoft: https://developercommunity.visualstudio.com/content/problem/426580/c-variadic-template-function-incorrectly-interacts.html

**Comment by ax3l** [comment] 2019-01-15 09:49
Can you please update the PR description with the known failing/working VS versions as long as we still know them? :)

**Comment by sbastrakov** [comment] 2019-01-15 13:40
For now I only know that the bug is present in VS 15.9.3 (my version), but not present in VS 15.8.6. However, I do not currenty have access to VS 15.8.6 and only know my mini-app works there, but alpaka was not tested.

**Comment by sbastrakov** [comment] 2019-01-16 13:03
Update: the latest version 15.9.5 also has this buggy behaviour.

**Comment by ax3l** [comment] 2019-01-16 13:49
Hm, upstream MSVC does not seem to have decent test coverage, from what it bugs out in releases during the last years.

**Comment by sbastrakov** [comment] 2019-01-17 10:04
Now I'm a bit puzzled. The tech support suggested removing `/permissive-` flag (enabled by default since VS 15.5) as a workaround  and for my mini-app this does indeed make it work properly. It seems to me we set this flag [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/053ce4f5bdbcf7738dff64e94170305343d2a73f/cmake/dev.cmake#L41). 

However, here is the puzzling part. After configuring alpaka on my machine this flag is somehow already disabled (don't understand why, guess I am missing smth simple). But the problem is still present anyways even with disabled flag. Although, again, for the mini-app disabling removes the effect.

**Comment by BenjaminW3** [comment] 2019-02-06 17:31
Could all the @ComputationalRadiationPhysics/alpaka-developers who have a microsoft account please upvote [this issue](https://developercommunity.visualstudio.com/content/problem/426580/c-variadic-template-function-incorrectly-interacts.html)?

**Comment by BenjaminW3** [comment] 2019-11-22 06:30
`"A fix for this issue has been internally implemented and is being prepared for release. We’ll update you once it becomes available for download."`

So it will finally be fixed in one of the next VS updates!

**Comment by sbastrakov** [comment] 2019-11-22 09:42
Let's hope. Thanks for info @BenjaminW3

**Comment by sbastrakov** [comment] 2020-01-23 08:15
They just updated the status to `"A fix for this issue is now available in preview release. Try out the fix by installing the most recent preview from https://visualstudio.microsoft.com/vs/preview/."`
Haven't tried it yet.

**Closed as completed** 2020-04-10 09:28 UTC
Labels: Type:Bug, Type:Testing, Backend:OpenMP, OS:Windows
