### ISSUE TITLE
check minimum dependencies e.g. boost in header

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1856] opened 2022-12-07 19:19 UTC
In cases, Cmake has not used the minimum required boost version is not checked in the code.
At least in cases where the stand alone headers are used the boost version should be checked.

see:  [CMake has not used](https://github.com/alpaka-group/alpaka/pull/1849#issuecomment-1333732481)

**Comment by bernhardmgruber** [comment] 2022-12-09 12:09
Isn't this a duplicate of #1636?

**Comment by j-stephan** [comment] 2022-12-09 12:31
Yes.

**Closed as completed by j-stephan** 2022-12-09 12:31 UTC
Labels: Type:Bug
