### ISSUE TITLE
Alpaka Build Error. 

### ISSUE THREAD

**Issue by hpcresearch-ht** [alpaka-group/alpaka#880] opened 2019-11-19 14:27 UTC
Hi 
I am getting this error while trying to build than example object. I have  enable CUDA , 
My system configrations : CentOS 7.7
Ram 16Gb
CUDA 10.1
GCC version : 7.3
 Thanks in advance
```
[  1%] Building NVCC (Device) object example/bufferCopy/CMakeFiles/bufferCopy.dir/src/bufferCopy_generated_bufferCopy.cpp.o
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp: In lambda function:
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:381:39: error: parameter packs not expanded with ‘...’:
                     auto boundTask([=](){return task(args...);});
                                       ^
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:381:39: note:         ‘args’
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:381:44: error: expansion pattern ‘args’ contains no argument packs
                     auto boundTask([=](){return task(args...);});
                                            ^
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp: In lambda function:
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:589:39: error: parameter packs not expanded with ‘...’:
                     auto boundTask([=](){return task(args...);});
                                       ^
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:589:39: note:         ‘args’
/home/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:589:44: error: expansion pattern ‘args’ contains no argument packs
                     auto boundTask([=](){return task(args...);});
                                            ^
/home/alpaka/include/alpaka/kernel/TaskKernelCpuThreads.hpp: In lambda function:
/home/alpaka/include/alpaka/kernel/TaskKernelCpuThreads.hpp:242:57: error: parameter packs not expanded with ‘...’:
                         blockThreadExecAcc(
                                                         ^
/home/alpaka/include/alpaka/kernel/TaskKernelCpuThreads.hpp:242:57: note:         ‘args’
/home/alpaka/include/alpaka/kernel/TaskKernelCpuThreads.hpp:242:62: error: expansion pattern ‘args’ contains no argument packs
                         blockThreadExecAcc(
```

**Comment by sbastrakov** [comment] 2019-11-19 14:49
Thanks for reporting @hpcresearch-ht . I will try to reproduce now. Are you using the latest release 0.3.5, or `develop` branch?

**Comment by hpcresearch-ht** [comment] 2019-11-19 14:53
Hi @sbastrakov  I have downloaded the master branch

**Comment by sbastrakov** [comment] 2019-11-19 14:56
@hpcresearch-ht sorry, I am confused. Alpaka has no `master` branch. (Used to, but not anymore).

**Comment by hpcresearch-ht** [comment] 2019-11-19 15:00
sorry its develop branch

**Comment by hpcresearch-ht** [comment] 2019-11-19 15:05
Sorry  its develop branch

I have cloned it using git clone https://github.com/ComputationalRadiationPhysics/alpaka.git

**Comment by sbastrakov** [comment] 2019-11-19 15:07
Unfortunately, I do not have CUDA 10.1 at hand. Tried alpaka `develop` branch with gcc 7.3.0 and CUDA 10.0. The problem did not appear. 
Sorry to bother again @hpcresearch-ht , are you using cmake? If so, could you also copy the initial cmake output when building (`-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
`, etc.). It has some alpaka specific macro output which tells what backends are enabled.

**Comment by hpcresearch-ht** [comment] 2019-11-19 15:09
Yes I am using cmake

**Comment by sbastrakov** [comment] 2019-11-19 15:10
Clarification: I meant the output when you do cmake out-of-source build with smth like
```
mkdir [alpaka_build_dir]
cd [alpaka_build_dir]
cmake [alpaka_repo] . 
cmake --build .
```

**Comment by hpcresearch-ht** [comment] 2019-11-19 15:11
The Cmake output

```
-- ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED
-- ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED
-- ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED
-- ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED
-- ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED
-- ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED
-- ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- Catch2: Using INTERNAL version 2.5.0
-- Configuring done
```

**Comment by sbastrakov** [comment] 2019-11-19 15:13
Thanks @hpcresearch-ht . Everything looks fine there. Then I will try to find a CUDA 10.1 system to really look into that, since on CUDA 10.0 it does not reproduce for me.

**Comment by hpcresearch-ht** [comment] 2019-11-19 15:16
@sbastrakov  Sorry to boher you . Is there other way to build without cmake

**Comment by sbastrakov** [comment] 2019-11-19 15:18
It is possible, but cmake is our preferred way. And it looks like the problem should not be caused by misconfiguration. So in my opinion after doing everything manually and potentially resolving problems and applying workarounds we have in the cmake configuration, you'll arrive at the same issue when compiling.

**Comment by hpcresearch-ht** [comment] 2019-11-19 15:19
okay Thanks @sbastrakov .

**Comment by sbastrakov** [comment] 2019-11-19 15:21
However, in case you have another compiler + CUDA configuration, maybe worth trying as a temporary way to make things work, while we are working on solving this issue.

**Comment by hpcresearch-ht** [comment] 2019-11-19 15:23
Yeah . I am on that  
Going to try with CUDA 10.0

**Comment by sbastrakov** [comment] 2019-11-21 09:09
@hpcresearch-ht did it work for you with CUDA 10.0 ?

**Comment by sbastrakov** [comment] 2019-11-21 10:32
@psychocoderHPC I think we can check if gcc 7.3. + CUDA 10.1 works on Taurus.

**Comment by psychocoderHPC** [comment] 2019-11-21 12:57
@hpcresearch-ht Could you please try to build all again in a clean build directory and post all output beginning with cmake.
I tried to reproduce the issue with gcc 7.3.0 and cuda 10.1.168 and all worked well.

**Comment by BenjaminW3** [comment] 2019-11-21 16:21
We should also have all those compiler <-> CUDA versions within our CI and it works there as well.
[See here!](https://github.com/ComputationalRadiationPhysics/alpaka/blob/a21ac3e5d83a21a3ed007aa399ea16f1e8d0f994/.travis.yml#L291-L292)

**Comment by sbastrakov** [comment] 2019-11-22 09:41
@BenjaminW3 thanks for linking that. However, I believe we only have all major gcc version + compatible CUDA, but not all variations of minor gcc versions (which would have probably been too much, to be fair).

**Comment by BenjaminW3** [comment] 2019-11-22 09:49
That is true, we install the latest update for the major version that is available for the given OS. However, this should likely be 7.3.

**Comment by ax3l** [comment] 2019-11-26 17:54
Looks to me like you are building without CMake and not setting `-std=c++11` or c++14 flags...

**Comment by sbastrakov** [comment] 2019-12-03 14:16
@hpcresearch-ht did any of the suggestions help?

**Comment by BenjaminW3** [comment] 2020-01-08 20:23
@hpcresearch-ht Do you have any update?

**Comment by BenjaminW3** [comment] 2020-01-14 13:47
I will close the issue for now. If there are any updates feel free to reopen.

**Closed as completed by BenjaminW3** 2020-01-14 13:47 UTC
Labels: State:Out Of Date?, Backend:CUDA
