### ISSUE TITLE
readthedocs does not build new documentation

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1036] opened 2020-06-08 13:41 UTC
I checked the config on https://readthedocs.org and triggered a manual build. So, I think the [webhook on GitHub](https://docs.readthedocs.io/en/stable/webhooks.html#github) is missing.

@alpaka-group/alpaka-admins 
Can anybody of the admins check, if the webhook is configured? I have not the right permission. If the hook is missing, @psychocoderHPC must handle it, because he has the permission on Alpaka and readthedocs.

**Comment by sbastrakov** [comment] 2020-06-08 17:30
I think this is a duplicate of #1032 reported earlier today?

**Comment by SimeonEhrig** [comment] 2020-06-09 07:54
No, it's a duplicate but they are related. See #1037

**Comment by psychocoderHPC** [comment] 2020-06-29 08:15
I fixed the hooks for readthedocs on Freiday all is working now.

**Closed as completed by psychocoderHPC** 2020-06-29 08:15 UTC
Labels: Type:Bug, Type:Documentation

**Comment by ax3l** [comment] 2020-07-16 23:34
fyi: you can now add read-the-docs as PR review build, so you don't have to wait until a PR is merged to see if it will break the sphinx build:

https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by SimeonEhrig** [comment] 2020-07-20 14:02
> fyi: you can now add read-the-docs as PR review build, so you don't have to wait until a PR is merged to see if it will break the sphinx build:
> 
> https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

@psychocoderHPC and I have set up the integration: #1091
