### ISSUE TITLE
Make vendor RNGs optional

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1955] opened 2023-06-13 08:48 UTC
Alpaka currenty looks for random number generator implementations provided by vendors when the corresponding backend is enabled. However, these may require additional dependencies which have to be setup, even in the case when the RNG functionality is not even needed.

As an example, enabling the HIP backend makes `rocrand` a required dependency, which is additional work to provide.

We should therefore make the RNGs an optional dependency. Either via a cmake option, a macro or just make the header auto-detect whether the dependency is present.

**Comment by j-stephan** [comment] 2023-06-13 12:48
This looks like a duplicate of #1810, no?

**Comment by bernhardmgruber** [comment] 2023-06-13 12:49
Yes.

**Closed as not planned** 2023-06-13 12:49 UTC
Labels: Type:Enhancement, Type:Install
