### ISSUE TITLE
request: make the dependency on hiprand/curand optional

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1929] opened 2023-03-10 12:10 UTC
Would it be possible to make the dependency on curand and hiprand optional, for example dependent on preprocessor macros ?

It would be OK to have it enabled by default, and give the possibility of disabling it, _e.g._ setting `-DALPAKA_DISABLE_RNG`.

The reason is that the CMS software does not use the random number generators in CUDA, HIP or Alpaka, but it needs to bring those libraries in as a dependency of Alpaka.

**Comment by j-stephan** [comment] 2023-03-10 13:10
Closing as duplicate of #1810.

**Closed as completed by j-stephan** 2023-03-10 13:10 UTC
Labels: State:Duplicate
